
GUIEditor = {
    gridlist = {},
    button = {},
    label = {}
}
addEventHandler("onClientResourceStart", resourceRoot,
    function()
        winstats = guiCreateWindow(0.65, 0.31, 0.34, 0.43, "Personaje #1234 - Nombre_Apellido", true)
        guiWindowSetSizable(winstats, false)

        tabs = guiCreateTabPanel(0.02, 0.08, 0.95, 0.89, true, winstats)

        tabprincial = guiCreateTab("Principal", tabs)

        name = guiCreateLabel(0.01, 0.04, 0.67, 0.11, "Nombre Completo: Nombre_Apellido", true, tabprincial)
        guiSetFont(name, "default-bold-small")
        guiLabelSetVerticalAlign(name, "center")
        sexo = guiCreateLabel(0.01, 0.27, 0.67, 0.11, "Sexo: Masculino", true, tabprincial)
        guiSetFont(sexo, "default-bold-small")
        guiLabelSetVerticalAlign(sexo, "center")
        nacio = guiCreateLabel(0.01, 0.15, 0.67, 0.11, "Nacionalidad: Colombiano", true, tabprincial)
        guiSetFont(nacio, "default-bold-small")
        guiLabelSetVerticalAlign(nacio, "center")
        edad = guiCreateLabel(0.01, 0.38, 0.67, 0.11, "Edad: 23", true, tabprincial)
        guiSetFont(edad , "default-bold-small")
        guiLabelSetVerticalAlign(edad , "center")
        nivel = guiCreateLabel(0.01, 0.49, 0.67, 0.11, "Nivel: 4", true, tabprincial)
        guiSetFont(nivel, "default-bold-small")
        guiLabelSetVerticalAlign(nivel, "center")
        ppizzero = guiCreateLabel(0.01, 0.65, 0.31, 0.11, "Pizzero: 1 lvl", true, tabprincial)
        guiSetFont(ppizzero, "default-bold-small")
        guiLabelSetVerticalAlign(ppizzero, "center")
        pbasurero = guiCreateLabel(0.01, 0.76, 0.31, 0.11, "Basurero: 1 lvl", true, tabprincial)
        guiSetFont(pbasurero, "default-bold-small")
        guiLabelSetVerticalAlign(pbasurero, "center")
        pjardinero = guiCreateLabel(0.01, 0.87, 0.31, 0.13, "Jardinero: 1 lvl", true, tabprincial)
        guiSetFont(pjardinero, "default-bold-small")
        guiLabelSetColor(pjardinero, 255, 254, 254)
        guiLabelSetVerticalAlign(pjardinero, "center")
        GUIEditor.label[9] = guiCreateLabel(0.33, 0.65, 0.31, 0.11, "Pescador: 1 lvl", true, tabprincial)
        guiSetFont(GUIEditor.label[9], "default-bold-small")
        guiLabelSetVerticalAlign(GUIEditor.label[9], "center")
        GUIEditor.label[10] = guiCreateLabel(0.33, 0.76, 0.31, 0.11, "Carpintero: 1 lvl", true, tabprincial)
        guiSetFont(GUIEditor.label[10], "default-bold-small")
        guiLabelSetVerticalAlign(GUIEditor.label[10], "center")
        GUIEditor.label[11] = guiCreateLabel(0.33, 0.87, 0.31, 0.13, "Camionero: 1 lvl", true, tabprincial)
        guiSetFont(GUIEditor.label[11], "default-bold-small")
        guiLabelSetVerticalAlign(GUIEditor.label[11], "center")

        tabsancion = guiCreateTab("Sanciones", tabs)

        GUIEditor.gridlist[1] = guiCreateGridList(0.01, 0.02, 0.98, 0.96, true, tabsancion)
        guiGridListAddColumn(GUIEditor.gridlist[1], "Nombre", 0.2)
        guiGridListAddColumn(GUIEditor.gridlist[1], "Tipo", 0.2)
        guiGridListAddColumn(GUIEditor.gridlist[1], "Motivo", 0.2)
        guiGridListAddColumn(GUIEditor.gridlist[1], "Autor", 0.2)
        guiGridListAddColumn(GUIEditor.gridlist[1], "Fecha", 0.2)

        tabextra = guiCreateTab("Extra", tabs)

        skin = guiCreateLabel(0.02, 0.03, 0.21, 0.09, "Skin: 123", true, tabextra)
        guiSetFont(skin, "default-bold-small")
        guiLabelSetVerticalAlign(skin, "center")
        vida = guiCreateLabel(0.02, 0.12, 0.21, 0.09, "vida: 100", true, tabextra)
        guiSetFont(vida, "default-bold-small")
        guiLabelSetVerticalAlign(vida, "center")
        cha = guiCreateLabel(0.02, 0.21, 0.21, 0.09, "Chaleco: 100", true, tabextra)
        guiSetFont(cha, "default-bold-small")
        guiLabelSetVerticalAlign(cha, "center")
        dinero = guiCreateLabel(0.02, 0.30, 0.42, 0.10, "Dinero en mano: $96390113", true, tabextra)
        guiSetFont(dinero, "default-bold-small")
        guiLabelSetVerticalAlign(dinero, "center")
        dinb = guiCreateLabel(0.02, 0.40, 0.42, 0.10, "Dinero en banco: $630358", true, tabextra)
        guiSetFont(dinb, "default-bold-small")
        guiLabelSetVerticalAlign(dinb, "center")
        radio = guiCreateLabel(0.02, 0.50, 0.42, 0.10, "Radio: -4.5 Hz", true, tabextra)
        guiSetFont(radio, "default-bold-small")
        guiLabelSetVerticalAlign(radio, "center")
        tele = guiCreateLabel(0.02, 0.60, 0.42, 0.10, "Telefono: 25486", true, tabextra)
        guiSetFont(tele, "default-bold-small")
        guiLabelSetVerticalAlign(tele, "center")
        rol = guiCreateLabel(0.02, 0.70, 0.42, 0.10, "Puntos de rol: X", true, tabextra)
        guiSetFont(rol, "default-bold-small")
        guiLabelSetVerticalAlign(rol, "center")
        adv = guiCreateLabel(0.02, 0.78, 0.42, 0.10, "Advertencias:", true, tabextra)
        guiSetFont(adv, "default-bold-small")
        guiLabelSetVerticalAlign(adv, "center")
        perso = guiCreateGridList(0.60, 0.12, 0.38, 0.38, true, tabextra)
        guiGridListAddColumn(perso, "Personajes", 0.9)
        persola = guiCreateLabel(0.68, 0.00, 0.21, 0.09, "Personajes:", true, tabextra)
        guiSetFont(persola, "default-bold-small")
        guiLabelSetHorizontalAlign(persola, "center", false)
        guiLabelSetVerticalAlign(persola, "center")
        GUIEditor.label[21] = guiCreateLabel(0.69, 0.51, 0.21, 0.09, "Serial:", true, tabextra)
        guiSetFont(GUIEditor.label[21], "default-bold-small")
        guiLabelSetHorizontalAlign(GUIEditor.label[21], "center", false)
        guiLabelSetVerticalAlign(GUIEditor.label[21], "center")
        serial = guiCreateLabel(0.43, 0.60, 0.57, 0.10, "SIN ENCONTRAR", true, tabextra)
        guiSetFont(GUIEditor.label[22], "default-bold-small")
        guiLabelSetColor(GUIEditor.label[22], 3, 254, 246)
        guiLabelSetHorizontalAlign(GUIEditor.label[22], "center", false)
        guiLabelSetVerticalAlign(GUIEditor.label[22], "center")
        GUIEditor.button[2] = guiCreateButton(0.04, 0.90, 0.26, 0.08, "Copiar Serial", true, tabextra)
        guiSetFont(GUIEditor.button[2], "default-bold-small")
        guiSetProperty(GUIEditor.button[2], "NormalTextColour", "FFFEFEFE")
        GUIEditor.label[23] = guiCreateLabel(0.69, 0.70, 0.21, 0.09, "IP:", true, tabextra)
        guiSetFont(GUIEditor.label[23], "default-bold-small")
        guiLabelSetHorizontalAlign(GUIEditor.label[23], "center", false)
        guiLabelSetVerticalAlign(GUIEditor.label[23], "center")
        GUIEditor.label[24] = guiCreateLabel(0.69, 0.80, 0.21, 0.08, "Comming Soon", true, tabextra)
        guiSetFont(GUIEditor.label[24], "default-bold-small")
        guiLabelSetColor(GUIEditor.label[24], 3, 254, 246)
        guiLabelSetHorizontalAlign(GUIEditor.label[24], "center", false)
        guiLabelSetVerticalAlign(GUIEditor.label[24], "center")
        GUIEditor.button[3] = guiCreateButton(0.32, 0.90, 0.26, 0.08, "Copiar IP", true, tabextra)
        guiSetFont(GUIEditor.button[3], "default-bold-small")
        guiSetProperty(GUIEditor.button[3], "NormalTextColour", "FFFEFEFE")




        cerrar = guiCreateButton(0.92, 0.76, 0.07, 0.03, "Cerrar", true)
        guiSetFont(cerrar, "default-bold-small")
        guiSetProperty(cerrar, "NormalTextColour", "FFFE1313") 
        guiSetVisible(winstats,false)   
        guiSetVisible(cerrar,false) 
    end
)




addEvent("winstats",true)
addEventHandler("winstats",root,function(pe,n,s,e)
	guiSetVisible(winstats,true)
	showCursor(true)
	guiSetVisible(cerrar,true)
	guiSetText(winstats,"Stats de: "..getPlayerName(localPlayer):gsub("_"," "))
	guiSetText(name,"Nombre Completo: "..getPlayerName(localPlayer):gsub("_"," "))
	guiSetText(sexo,"Sexo: "..s)
	guiSetText(nacio,"Nacionalidad: "..n)
	guiSetText(edad,"Edad: "..e)
	guiSetText(nivel,"Nivel: "..(getElementData(localPlayer,"Nivel")or 1))
	guiSetText(ppizzero,"Pizzero: "..(getElementData(localPlayer,"Pizzero:Nivel") or 1).." lvl "..(getElementData(localPlayer,"Pizzero:Exp") or 0).." Exp")
	guiSetText(pbasurero,"Basurero: "..(getElementData(localPlayer,"Basurero:Nivel") or 1).." lvl "..(getElementData(localPlayer,"Basurero:Exp") or 0).." Exp")
	guiSetText(pjcamion,"Camionero: "..(getElementData(localPlayer,"Camionero:Nivel") or 1).." lvl "..(getElementData(localPlayer,"Camionero:Exp") or 0).." Exp")
	guiSetText(pjardinero,"Jardinero: "..(getElementData(localPlayer,"Roleplay:ExpJobJardinero") or 1).." lvl")
	guiSetText(pcarpintero,"Carpintero: "..(getElementData(localPlayer,"Roleplay:ExpJobCarpintero") or 1).." lvl")
	guiSetText(pcarpintero,"Taxista: "..(getElementData(localPlayer,"Taxista:Exp") or 1).." lvl")
--
    guiSetText(skin,"Skin: #"..getElementModel(localPlayer))
    guiSetText(vida,"Vida: "..math.floor(localPlayer:getHealth()))
    guiSetText(cha,"Chaleco: "..getPedArmor(localPlayer))
    guiSetText(dinero,"Dinero en Mano: "..getPlayerMoney())
    guiSetText(dinb,"Dinero en Banco: "..(getElementData(localPlayer,"Roleplay:bank_balance") or 0))
    guiSetText(radio,"Radio: "..(getElementData(localPlayer,"frecuencia") or 0).." Hz")
    guiSetText(tele,"Telefono: "..(getElementData(localPlayer,"Roleplay:NumeroTelefono") or 0))
    guiSetText(rol,"Puntos de rol: +"..(localPlayer:getData("+rol") or 0).."  "..(localPlayer:getData("-rol") or 0))
    guiSetText(adv,"Advertencias: #"..(localPlayer:getData("warn") or 0))
	
	guiSetText(serial, getPlayerSerial())
	guiGridListClear(perso)
	for i,v in ipairs(pe) do
		local row = guiGridListAddRow(perso)
		guiGridListSetItemText(perso, row, 1, v.Cuenta, false, true)
		guiGridListSetItemData(perso, row, 1, v.Cuenta)
	end

end)



addEventHandler("onClientGUIClick",resourceRoot,function()
	if source == cerrar then
		guiSetVisible(winstats,false)
		guiSetVisible(cerrar,false)
		showCursor(false)
	end
end)